[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_APIKEY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_APIKEY}"